title: Interactive Media Capstone
description: Compiled resources/documentation for my 2021-2022 Interactive Media Capstone.
author:
  name: Benjamin Pang
  email: ben.10@nyu.edu

minima:
  social_links:
    github: molarmanful
    instagram: bandidojim

remote_theme: jekyll/minima
